### ISSUE TITLE
笔记有一处小错误

### ISSUE THREAD

**Issue by Leopard-S** [mathors/Postgraduate-Advanced-Mathematics#3]
6极限存在准则两个重要极限：（二）的第二个推广的接近值写错了，不是趋近无限，而是趋近0.

**Comment by wmathor** [comment]
![](https://user-images.githubusercontent.com/32392878/87261128-a3a1c980-c4e7-11ea-9bd7-b7271b21ae2a.png)
你指的是这个吗？
只要(1+a)^b中，a趋于0，指数的b趋于无限就行了
